<%@page pageEncoding="utf-8" contentType="text/html; charset=utf-8"%>
<h1>A csata</h1>

<p>A küldetésed során nem fogsz a világűrben harcba keveredni. A Birodalom alatt az emberek nem viselhetnek fegyvert, és mivel kereskedőként fogsz utazni, az űrhajód is fegyvertelen lesz. A bolygók közti útjaid a természetes veszélyektől eltekintve eseménymentesek lesznek. Meteoresők természetesen bármikor előfordulhatnak, de a hajó pajzsai elég erősek ahhoz, hogy kivédjék az ilyesféle kellemetlen meglepetéseket.</p>
<p>A hajó pajzsát alkotó erőtér alkalmas űrhajók védelmére, mivel a külső objektumok sebességére reagál. Ha egy objektum elég nagy és elég gyors ahhoz, hogy kárt tehessen az űrhajóban, az erőtér nem engedi át. Ez az erőlcres védekezési mód sajnos nem használható egyes személyek védelmére: könnyen elképzelhető, hogy átengedne egy olyan tárgyat, mely egy űrhajónak nem, de egy embernek vagy egy árkádnak ártani tudna. Arról nem is beszélve, hogy az erőteret létrehozó berendezés nagy és ormótlan, még a miniatürizáció jelenlegi előrehaladott állapota mellett is. Természetesen más problémák is vannak: számtalan olyan tárgy létezik, amely az űrben nem, de a hétköznapi környezetben megtalálható, és interferál az erőtérrel, nem is beszélve a nagy tárgyaknak az erőtérbe csapódása által keltett lökéshullámokról, mely puha bőrű lények esetében legalább olyan ártalmas lehet, mint maga az erőtér által lefékezett tárgy.</p>
<p>Így tehát a huszonötödik században nem létezik személyes erőpajzs, viszont az elmúlt századok során számtalan gyilkos fegyvert fejlesztettek ki &ndash; ágyúkat, lézereket, fotongránátokat, gravitációs bombákat, dezintegrátorokat. Ezen fegyverek némelyike annyira erős, hogy komoly problémát okoz az árkád hatóságoknak, akik állandóan rettegnek egy esetleges felkeléstől. Bár az emberek nem viselnek fegyvert, árkád őrzőik viszont igen, és előfordulhatnak alkalmak, amikor a fegyvertelen emberek legyűrnek egy árkádot, és elveszik a fegyverét, ily módon lassan egy hadsereg felállításához elegendő fegyvert gyűjtve. A megoldás rendkívül egyszeri volt: amikor a Birodalom kellőképpen megszilárdult, minden erős fegyvert visszaszállítottak az Arcadionra, és azóta is ott tárolják őket. Az árkádok csak kevésbé erős fegyvereket viselnek (lézerkardokat, elektromos korbácsokat), csak olyanokat, melyek esetleges elvesztése nem okoz komoly problémát a Birodalom biztonsága szempontjából.</p>
<p>Te illegális úton jutottál hozzá a lézerkardodhoz. Egy lézerkardot elég könnyű átvinni az ellenőrzőpontokon &ndash; egészen addig, amíg nem vizsgálnak át teljes alapossággal &ndash;, mivel a lézerkard kikapcsolt állapotban nem több egy rövidke, tenyérbe simuló fémrúdnál, melyen számos kapcsoló és gomb található. A bonyolult miniatűr elektronika a fémrúd belsejében rejtőzik.</p>
<p>A küldetésed során ez lesz a fegyvered. Ez és az <span class="attribute">ÜGYESSÉGED</span> elég lesz az utad során felbukkanó ellenfelek legyőzésére, mivel nekik sem lesznek erősebb fegyvereik. Ha szerencsés vagy, és a megfelelő döntéseket hozod, néha erősebb fegyverekhez is hozzájuthatsz; természetesen olyan ellenfelekkel is találkozhatsz néha, akiknek erősebbek a fegyverei, mint a tieid. Ha a könyvben másképp nem utasítunk, a harcot mindig az alábbiak szerint kell megvívnod:</p>
<p>A közelharc szabályai pontosan megegyeznek a többi Fantázia Harcos könyvben leírtakkal, ezért, ha már ismered őket, nyugodtan átlapozhatod ezt a szakaszt. Először, is jegyezd fel az ellenfeled <span class="attribute">ÜGYESSÉG</span> és <span class="attribute">ÉLETERŐ</span> pontjait a következő üres Találkozás Ellenfelekkel rovatba a kalandlapodon. Ezek az értékek minden egyes ellenfélre meg lesznek adva, ha harcra kerül a sor. A harc menete a következő:</p>

<ol>
    <li>A harc un. körökből áll. Minden körben a küzdő felek megpróbálnak sebezni ellenfelükön.</li>
    <li>Dobj két kockával az ellenfelednek. Add a dobáshoz az ÜGYESSÉG pontjait. Az összeg az ellenfeled Támadóereje.</li>
    <li>Dobj két kockával magadnak. Add hozzá a saját <span class="attribute">ÜGYESSÉGEDET</span>. Az összeg a te Támadóerőd.</li>
    <li>Ha a Támadóerőd nagyobb, mint az ellenfélé, megsebezted őt: ugorj az 5-ös pontra. Ha az ellenfeled Támadóereje nagyobb, mint a tied, ő sebzett meg téged: ugorj a 6-os pontra. Ha a két Támadóerő egyenlő, kölcsönösen kivédtétek egymás támadását. Folytassátok tovább a harcot a következő körrel (2. pont).</li>
    <li>Megsebezted az ellenfeled, vonj le 2 pontot az <span class="attribute">ÉLETEREJÉBŐL</span>. (Használhatod a <span class="attribute">SZERENCSÉDET</span> is, hogy még nagyobb sebet okozz &ndash; lejjebb részletesen leírjuk, hogyan.)</li>
    <li>Az ellenfeled eltalált, vonj le 2 pontot az <span class="attribute">ÉLETERŐDBŐL</span>. (Ismét használhatod a <span class="attribute">SZERENCSÉDET</span> &ndash; lejjebb elolvashatod, hogyan.)</li>
    <li>Jegyezd fel az <span class="attribute">ÉLETERŐ</span> pontok megváltozását. (Ha használtad a <span class="attribute">SZERENCSÉDET</span>, jegyezd fel a SZERENCSE pontok megváltozását &ndash; lásd alább.)</li>
    <li>Kezdj újabb kört az akkor éppen aktuális ÜGYESSÉG pontjaiddal. Ismételd a 2&ndash;7. lépéseket egészen addig, amíg valamelyik küzdő fél <span class="attribute">ÉLETERŐ</span> pontjai nullára nem csökkennek (meghalt). Ebben a kalandban nincs lehetőség a harcból való elmenekülésre.</li>
</ol>