<%@page pageEncoding="utf-8" contentType="text/html; charset=utf-8"%>
<h2><span class="attribute">ÜGYESSÉG</span>, <span class="attribute">ÉLETERŐ</span> ÉS <span class="attribute">SZERENCSE</span></h2>

<p>Dobj egy kockával. Ha a harcos szerepét választottad (az egyszerű játékot játszod), adj 6-ot a dobott számhoz, és az összeget írd be a Kalandlap <span class="attribute">ÜGYESSÉG</span> négyzetébe. Ha a varázsló szerepét választottad (a magasabb fokozatú játékot játszod), csupán 4-et adj a dobott számhoz, és az összeget írd be a Kalandlapra. A varázslók gyengébben küzdenek, mint a harcosok, viszont ezt a hiányosságukat varázslótudományukkal ellensúlyozzák.</p>
<p>Dobj mindkét kockával, és az eredményhez adj 12-t, majd a kapott számot írd be az <span class="attribute">ÉLETERŐ</span> négyzetbe.</p>
<p>Van egy <span class="attribute">SZERENCSE</span> rovat is. Ehhez egy kockával dobj, és 6-ot adj az eredményhez, majd az összeget írd be a <span class="attribute">SZERENCSE</span> négyzetbe.</p>
<p>Különböző okok miatt, melyeket majd részletesen elmagyarázunk, <span class="attribute">ÜGYESSÉG</span>, <span class="attribute">ÉLETERŐ</span> és <span class="attribute">SZERENCSE</span> pontjaid a kalandok során folyamatosan változni fognak. Pontosan kell vezetned őket, ezért azt tanácsoljuk, hogy kis betűkkel írj a négyzetekbe, vagy tarts kéznél radírt. De soha ne töröld ki a Kezdő pontjaidat, mert szerezhetsz ugyan további <span class="attribute">ÜGYESSÉG</span>, <span class="attribute">ÉLETERŐ</span> és <span class="attribute">SZERENCSE</span> pontokat, de összegük soha nem lépheti túl a <em>Kezdeti</em> értéket, kivéve azokat a ritka eseteket, amikor erre külön utasítást kapsz.</p>
<p><span class="attribute">ÜGYESSÉG</span> pontjaid kardvívó tudásodat és általános harckészségedet mutatják. Nem árt minél több ilyen pontra szert tenni.</p>
<p><span class="attribute">ÉLETERŐ</span> pontjaid jelzik kondíciódat, akaraterődet, hogy túlélj egy-egy helyzetet, továbbá eltökéltségedet és állóképességedet; minél magasabb az <span class="attribute">ÉLETERŐ</span> pontszámod, annál hosszabb ideig maradhatsz életben. <span class="attribute">SZERENCSE</span> pontjaid mutatják, mennyire vagy szerencsés ember. A szerencse és a varázslat az úr abban a fantasztikus birodalomban, amelybe most behatolsz.</p>
