package hu.zagor.gamebooks.selenium.ff.ff;

import hu.zagor.gamebooks.selenium.ff.BasicFfSeleniumTest;

import java.util.Arrays;

import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

/**
 * Selenium test for book KJK9.
 * @author Tamas_Szekeres
 */
@Test
public class HuTrialOfChampionsST extends BasicFfSeleniumTest {

    @BeforeClass
    public void setUpClass() {
        startBook("990162009", "kjk9");
    }

    public void testDeathByCrusher() {
        setUpRandomRolls(Arrays.asList(3, 4, 1, 6, 1, 4, 1, 5, 5, 3, 5, 5, 4, 2, 5, 2, 4, 5, 3, 3, 1, 2, 2, 5, 3, 2));
        goToPosition("0", "background");
        verifyPosition(0, 1);
        goToPosition(0, 1);
        verifyPosition(0, 49);
        verifyPosition(1, 292);
        goToPosition(0, 49);
        verifyPosition(0, 22);
        goToPosition(0, 22);
        verifyPosition(0, 310);
        verifyPosition(1, 107);
        goToPosition(1, 107);
        doAttributeCheck();
        goToPosition(3, 250);
        doRandomRoll();
        goToPosition(1, 202);
        verifyPosition(0, 136);
        goToPosition(0, 136);
        verifyPosition(0, 275);
        verifyPosition(1, 275);
        goToPosition(0, 275);
        verifyPosition(0, 56);
        goToPosition(0, 56);
        prepareLuckSettings(false, false, false);
        attackEnemy("1");
        goToPosition(1, 343);
    }

    public void testDeathByBoneDemon() {
        setUpRandomRolls(Arrays.asList(5, 5, 3, 3, 1, 4, 2, 4, 2, 1, 1, 5, 4, 4, 3, 1, 1, 4, 3, 5, 4, 2, 5, 2, 2, 4, 1, 1, 5, 2, 5, 1, 2, 4, 6, 5, 4, 6, 4, 1, 5, 3, 4,
            3, 3, 3, 2, 3, 3, 3, 1, 1, 5, 6, 5, 1, 5, 1, 2, 3, 5, 5, 4, 5, 5, 1, 4, 5, 5, 4, 4, 5, 3, 3, 5, 3, 2, 3, 4, 6, 5, 6, 5, 1, 1, 1, 5, 3, 1, 4, 5, 3, 3, 1, 2,
            5, 5, 2, 6, 2, 2, 1, 5, 5, 1, 6, 3, 3, 6, 2, 4, 4, 5, 3, 5, 1, 4, 2, 2, 2, 2, 1, 3, 6, 3, 6, 1, 2, 4, 4, 1, 3, 6, 5, 3, 3, 4, 3, 3, 4, 5, 5, 4, 2, 6, 2, 4,
            5, 1, 1, 5, 1, 2, 3, 1, 3, 4, 2, 5, 2, 3, 5, 5, 5, 6, 1, 6, 5, 1, 6, 3, 5, 2, 2, 6, 6, 5, 1, 4, 2, 5, 6, 6, 2, 1, 5, 4, 4, 5, 4, 1, 4, 3, 6, 4, 2, 3, 4, 5,
            2, 5, 5, 3, 1, 5, 5, 2, 4, 5, 3, 6, 1, 3, 6, 1, 5, 2, 5, 1, 1, 3, 5, 5, 4, 2, 2, 5, 4, 5, 1, 5, 4, 4, 1, 4, 4, 3, 2, 2, 1, 4, 1, 3, 3, 6, 6, 1, 4, 2, 1, 3,
            1, 1, 4, 4, 2, 5, 1, 3, 5, 2, 2, 4, 6, 5, 3, 4, 3, 6, 2, 5, 1, 5, 3, 1, 1, 2, 4, 6, 1, 3, 5, 5, 4, 3, 1, 3, 4, 3, 6, 6, 1, 2, 5, 2, 4, 3, 1, 4, 1, 2, 4, 5,
            1, 2, 2, 4, 3, 5, 6, 5, 2, 4, 4, 2, 3, 1, 1, 5, 2, 5, 3, 3, 5, 1, 4));
        goToPosition("0", "background");
        verifyPosition(0, 1);
        goToPosition(0, 1);
        verifyPosition(0, 49);
        verifyPosition(1, 292);
        goToPosition(0, 49);
        verifyPosition(0, 22);
        goToPosition(0, 22);
        verifyPosition(0, 310);
        verifyPosition(1, 107);
        goToPosition(0, 310);
        doAttributeCheck();
        goToPosition(1, 225);
        doAttributeCheck();
        goToPosition(2, 360);
        verifyPosition(0, 136);
        goToPosition(0, 136);
        verifyPosition(0, 275);
        verifyPosition(1, 275);
        goToPosition(1, 275);
        verifyPosition(0, 175);
        goToPosition(0, 175);
        doRandomRoll();
        goToPosition(0, 31);
        doAttributeCheck();
        goToPosition(0, 66);
        doRandomRoll();
        goToPosition(1, 189);
        verifyPosition(0, 113);
        goToPosition(0, 113);
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        goToPosition(0, 237);
        doAttributeCheck();
        goToPosition(0, 94);
        verifyPosition(0, 297);
        verifyPosition(1, 9);
        goToPosition(0, 297);
        verifyPosition(0, 368);
        verifyPosition(1, 131);
        goToPosition(0, 368);
        doAttributeCheck();
        goToPosition(1, 73);
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        goToPosition(0, 196);
        verifyPosition(0, 120);
        goToPosition(0, 120);
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        goToPosition(0, 61);
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        goToPosition(0, 261);
        verifyPosition(0, 374);
        verifyPosition(1, 82);
        goToPosition(0, 374);
        prepareLuckSettings(false, false, false);
        attackEnemy("6");
        prepareLuckSettings(false, false, false);
        attackEnemy("6");
        prepareLuckSettings(false, false, false);
        attackEnemy("6");
        prepareLuckSettings(false, false, false);
        attackEnemy("6");
        goToPosition(0, 52);
        verifyPosition(0, 36);
        verifyPosition(1, 82);
        goToPosition(0, 36);
        verifyPosition(0, 82);
        takeItem("3004");
        goToPosition(0, 82);
        verifyPosition(0, 229);
        verifyPosition(1, 304);
        goToPosition(1, 304);
        verifyPosition(1, 27);
        verifyPosition(2, 152);
        verifyPosition(3, 355);
        goToPosition(3, 355);
        doAttributeCheck();
        goToPosition(0, 100);
        prepareLuckSettings(false, false, false);
        attackEnemy("7");
        prepareLuckSettings(false, false, false);
        attackEnemy("7");
        prepareLuckSettings(false, false, false);
        attackEnemy("7");
        goToPosition(0, 19);
        verifyPosition(0, 70);
        verifyPosition(1, 328);
        goToPosition(1, 328);
        verifyPosition(0, 27);
        verifyPosition(1, 152);
        verifyPosition(2, 229);
        goToPosition(1, 152);
        verifyPosition(0, 117);
        goToPosition(0, 117);
        verifyPosition(0, 179);
        verifyPosition(1, 229);
        goToPosition(0, 179);
        verifyPosition(0, 12);
        verifyPosition(1, 214);
        goToPosition(0, 12);
        verifyPosition(0, 246);
        verifyPosition(1, 346);
        goToPosition(0, 246);
        verifyPosition(0, 186);
        verifyPosition(1, 346);
        goToPosition(0, 186);
        prepareLuckSettings(false, false, false);
        attackEnemy("8");
        prepareLuckSettings(false, false, false);
        attackEnemy("8");
        prepareLuckSettings(false, false, false);
        attackEnemy("8");
        prepareLuckSettings(false, false, false);
        attackEnemy("9");
        prepareLuckSettings(false, false, false);
        attackEnemy("9");
        goToPosition(0, 142);
        verifyPosition(0, 124);
        verifyPosition(1, 171);
        verifyPosition(2, 300);
        verifyPosition(3, 346);
        goToPosition(2, 300);
        verifyPosition(0, 124);
        verifyPosition(1, 346);
        goToPosition(1, 346);
        verifyPosition(0, 59);
        verifyPosition(1, 150);
        goToPosition(0, 59);
        verifyPosition(0, 91);
        verifyPosition(1, 150);
        goToPosition(0, 91);
        doAttributeCheck();
        goToPosition(0, 332);
        verifyPosition(0, 219);
        goToPosition(0, 219);
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        goToPosition(0, 252);
        verifyPosition(0, 115);
        verifyPosition(1, 307);
        verifyPosition(2, 150);
        goToPosition(0, 115);
        verifyPosition(0, 173);
        verifyPosition(1, 307);
        verifyPosition(2, 150);
        goToPosition(0, 173);
        verifyPosition(0, 307);
        verifyPosition(1, 150);
        takeItem("3004");
        goToPosition(0, 307);
        verifyPosition(0, 233);
        verifyPosition(1, 272);
        verifyPosition(2, 150);
        goToPosition(0, 233);
        verifyPosition(0, 272);
        verifyPosition(1, 150);
        goToPosition(0, 272);
        verifyPosition(0, 205);
        verifyPosition(1, 150);
        goToPosition(0, 205);
        verifyPosition(2, 384);
        goToPosition(2, 384);
        doAttributeCheck();
        goToPosition(1, 265);
    }

    public void testDeathBySouthron() {
        setUpRandomRolls(Arrays.asList(4, 5, 3, 2, 2, 3, 4, 5, 4, 3, 5, 5, 4, 4, 1, 1, 1, 3, 1, 3, 4, 1, 5, 3, 2, 4, 5, 5, 5, 4, 5, 3, 6, 1, 3, 3, 5, 2, 2, 6, 6, 2, 1,
            3, 5, 5, 3, 5, 2, 3, 4, 5, 4, 4, 2, 3, 1, 2, 6, 3, 4, 4, 3, 3, 2, 4, 4, 5, 3, 1, 3, 2, 1, 4, 4, 1, 5, 2, 4, 1, 1, 4, 6, 4, 5, 2, 3, 2, 1, 2, 2, 4, 1, 1, 3,
            4, 3, 1, 6, 4, 3, 5, 4, 6, 1, 6, 1, 5, 5, 1, 1, 2, 5, 4, 5, 2, 5, 1, 1, 6, 6, 5, 4, 2, 5, 4, 5, 3, 2, 1, 6, 5, 4, 5, 6, 4, 2, 2, 5, 5, 2, 5, 5, 1, 2, 2, 2,
            6, 6, 2, 1, 3, 5, 4, 2, 1, 5, 1, 2, 1, 1, 6, 2, 3, 3, 4, 1, 5, 2, 1, 3, 2, 6, 4, 5, 3, 6, 5, 5, 4));
        goToPosition("0", "background");
        verifyPosition(0, 1);
        goToPosition(0, 1);
        verifyPosition(0, 49);
        verifyPosition(1, 292);
        goToPosition(1, 292);
        verifyPosition(0, 22);
        goToPosition(0, 22);
        verifyPosition(0, 310);
        verifyPosition(1, 107);
        goToPosition(0, 310);
        doAttributeCheck();
        goToPosition(1, 225);
        doAttributeCheck();
        goToPosition(0, 360);
        verifyPosition(0, 136);
        goToPosition(0, 136);
        verifyPosition(0, 275);
        verifyPosition(1, 275);
        goToPosition(1, 275);
        verifyPosition(0, 175);
        goToPosition(0, 175);
        doRandomRoll();
        goToPosition(0, 31);
        doAttributeCheck();
        goToPosition(0, 66);
        doRandomRoll();
        goToPosition(1, 189);
        verifyPosition(0, 113);
        goToPosition(0, 113);
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        goToPosition(0, 237);
        doAttributeCheck();
        goToPosition(0, 94);
        verifyPosition(0, 297);
        verifyPosition(1, 9);
        goToPosition(1, 9);
        doAttributeCheck();
        goToPosition(1, 73);
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        goToPosition(0, 196);
        verifyPosition(0, 120);
        goToPosition(0, 120);
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        goToPosition(0, 61);
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
    }

    public void testKilledInTheArena() {
        setUpRandomRolls(Arrays.asList(1, 5, 6, 1, 4, 5, 5, 5, 5, 1, 3, 1, 5, 4, 3, 1, 3, 4, 4, 2, 4, 2, 2, 6, 2, 5, 5, 2, 6, 4, 4, 1, 5, 2, 6, 2, 1, 5, 2, 5, 4, 3, 5,
            5, 4, 5, 1, 3, 6, 4, 3, 5, 5, 2, 2, 5, 3, 2, 1, 1, 2, 1, 2, 2, 6, 4, 5, 4, 3, 3, 1, 2, 3, 4, 2, 4, 1, 3, 5, 4, 2, 4, 1, 4, 3, 3, 3, 4, 3, 3, 4, 2, 1));
        goToPosition("0", "background");
        verifyPosition(0, 1);
        goToPosition(0, 1);
        verifyPosition(0, 49);
        verifyPosition(1, 292);
        goToPosition(0, 49);
        verifyPosition(0, 22);
        goToPosition(0, 22);
        verifyPosition(0, 310);
        verifyPosition(1, 107);
        goToPosition(1, 107);
        doAttributeCheck();
        goToPosition(2, 360);
        verifyPosition(0, 136);
        goToPosition(0, 136);
        verifyPosition(0, 275);
        verifyPosition(1, 275);
        goToPosition(1, 275);
        verifyPosition(0, 175);
        goToPosition(0, 175);
        doRandomRoll();
        goToPosition(1, 189);
        verifyPosition(0, 113);
        goToPosition(0, 113);
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(true, false, false);
        attackEnemy("2");
        prepareLuckSettings(true, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        goToPosition(0, 237);
        doAttributeCheck();
        goToPosition(0, 94);
        verifyPosition(0, 297);
        verifyPosition(1, 9);
        goToPosition(1, 9);
        doAttributeCheck();
        goToPosition(0, 166);
        verifyPosition(0, 183);
        verifyPosition(1, 349);
        verifyPosition(2, 316);
        goToPosition(0, 183);
        doAttributeCheck();
        goToPosition(1, 387);
    }

    public void testDeathByLicheQueensGloves() {
        setUpRandomRolls(Arrays.asList(1, 6, 3, 2, 6, 1, 1, 3, 3, 2, 3, 3, 2, 1, 1, 4, 5, 2, 4, 2, 1, 5, 3, 3, 2, 2, 4, 2, 5, 5, 1, 5, 5, 3, 4, 5, 4, 3, 4, 4, 6, 3, 1,
            1, 2, 2, 4, 4, 6, 5, 6, 1, 5, 3, 5, 3, 2, 4, 3, 2, 6, 1, 5, 4, 5, 2, 3, 5, 6, 2, 6, 2, 2, 4, 3, 5, 3, 4, 5, 3, 5, 1, 5, 5, 3, 3, 4, 2, 5, 2, 1, 5, 5, 4, 4,
            5, 3, 6, 4, 1, 3, 3, 5, 1, 2, 1, 5, 3, 4, 2, 2, 2, 3, 3, 6, 5, 4, 1, 1, 4, 1, 5, 6, 6, 4, 5, 3, 2, 6, 3, 1, 4, 3, 1, 1, 3, 3, 3, 1, 6, 1, 1, 2, 6, 1, 1, 6,
            5, 2, 4, 1, 5, 3, 4, 2, 3, 2, 1, 3, 3, 5, 2, 5, 2, 2, 5, 4, 4, 3, 3, 5, 2, 2, 1, 1, 3, 2, 5, 4, 3, 2, 5, 6, 4, 4, 6, 3, 6, 3, 6, 1, 1, 3, 3, 4, 2, 6, 4, 5,
            1, 5, 3, 3, 2, 4, 1, 1, 5, 2, 5, 6, 3, 1, 1, 5, 4, 5, 4, 3, 6, 1, 2, 4, 1, 4, 5, 4, 5, 2, 3, 3, 2, 1, 4, 4, 1, 3, 2, 3, 5, 4, 4, 1, 4, 4, 3, 4, 4, 5, 6, 5,
            6, 2, 5, 4, 6, 1, 4, 1, 4, 4, 2, 1, 1, 4, 5, 3, 3, 4, 1, 4, 3, 3, 3, 2, 6, 6, 3, 2, 1, 1, 1, 4, 2, 1, 5, 3, 3, 5, 1, 2, 1, 2, 1, 1, 2, 5, 2, 1, 5, 3, 4, 5,
            3, 5, 2, 5, 2, 2, 2, 4, 5, 5, 5, 5, 1, 5, 6, 3, 6, 2, 3, 1, 6, 5, 1, 2, 5, 4, 4, 1, 6, 3, 4, 2, 5, 3, 6, 4, 3, 1, 2, 1, 2, 5, 5, 1, 2, 4, 2, 2, 1, 3, 1, 3,
            5, 4, 4, 4, 3, 5, 5, 3, 3));
        goToPosition("0", "background");
        verifyPosition(0, 1);
        goToPosition(0, 1);
        verifyPosition(0, 49);
        verifyPosition(1, 292);
        goToPosition(0, 49);
        verifyPosition(0, 22);
        goToPosition(0, 22);
        verifyPosition(0, 310);
        verifyPosition(1, 107);
        goToPosition(1, 107);
        doAttributeCheck();
        goToPosition(2, 360);
        verifyPosition(0, 136);
        goToPosition(0, 136);
        verifyPosition(0, 275);
        verifyPosition(1, 275);
        goToPosition(1, 275);
        verifyPosition(0, 175);
        goToPosition(0, 175);
        doRandomRoll();
        goToPosition(0, 31);
        doAttributeCheck();
        goToPosition(0, 66);
        doRandomRoll();
        goToPosition(0, 255);
        doAttributeCheck();
        goToPosition(0, 66);
        doRandomRoll();
        goToPosition(1, 189);
        verifyPosition(0, 113);
        goToPosition(0, 113);
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        goToPosition(0, 237);
        doAttributeCheck();
        goToPosition(0, 94);
        verifyPosition(0, 297);
        verifyPosition(1, 9);
        goToPosition(0, 297);
        verifyPosition(0, 368);
        verifyPosition(1, 131);
        goToPosition(1, 131);
        doAttributeCheck();
        goToPosition(1, 210);
        doRandomRoll();
        goToPosition(1, 393);
        verifyPosition(0, 159);
        verifyPosition(1, 120);
        goToPosition(1, 120);
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        goToPosition(0, 61);
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        goToPosition(0, 261);
        verifyPosition(0, 374);
        verifyPosition(1, 82);
        goToPosition(0, 374);
        prepareLuckSettings(false, false, false);
        attackEnemy("6");
        prepareLuckSettings(false, false, false);
        attackEnemy("6");
        prepareLuckSettings(false, false, false);
        attackEnemy("6");
        goToPosition(0, 52);
        verifyPosition(0, 36);
        verifyPosition(1, 82);
        goToPosition(0, 36);
        verifyPosition(0, 82);
        takeItem("3004");
        goToPosition(0, 82);
        verifyPosition(0, 229);
        verifyPosition(1, 304);
        goToPosition(1, 304);
        verifyPosition(1, 27);
        verifyPosition(2, 152);
        verifyPosition(3, 355);
        goToPosition(3, 355);
        doAttributeCheck();
        goToPosition(0, 100);
        prepareLuckSettings(false, false, false);
        attackEnemy("7");
        prepareLuckSettings(false, false, false);
        attackEnemy("7");
        prepareLuckSettings(false, false, false);
        attackEnemy("7");
        prepareLuckSettings(false, false, false);
        attackEnemy("7");
        goToPosition(0, 19);
        verifyPosition(0, 70);
        verifyPosition(1, 328);
        goToPosition(0, 70);
        verifyPosition(0, 328);
        goToPosition(0, 328);
        verifyPosition(0, 27);
        verifyPosition(1, 152);
        verifyPosition(2, 229);
        goToPosition(1, 152);
        verifyPosition(0, 117);
        goToPosition(0, 117);
        verifyPosition(0, 179);
        verifyPosition(1, 229);
        goToPosition(0, 179);
        verifyPosition(0, 12);
        verifyPosition(1, 214);
        goToPosition(0, 12);
        verifyPosition(0, 246);
        verifyPosition(1, 346);
        goToPosition(0, 246);
        verifyPosition(0, 186);
        verifyPosition(1, 346);
        goToPosition(0, 186);
        prepareLuckSettings(false, false, false);
        attackEnemy("8");
        prepareLuckSettings(false, false, false);
        attackEnemy("8");
        prepareLuckSettings(false, false, false);
        attackEnemy("8");
        prepareLuckSettings(false, false, false);
        attackEnemy("9");
        prepareLuckSettings(false, false, false);
        attackEnemy("9");
        goToPosition(0, 142);
        verifyPosition(0, 124);
        verifyPosition(1, 171);
        verifyPosition(2, 300);
        verifyPosition(3, 346);
        goToPosition(2, 300);
        verifyPosition(0, 124);
        verifyPosition(1, 346);
        goToPosition(1, 346);
        verifyPosition(0, 59);
        verifyPosition(1, 150);
        goToPosition(0, 59);
        verifyPosition(0, 91);
        verifyPosition(1, 150);
        goToPosition(0, 91);
        doAttributeCheck();
        goToPosition(0, 332);
        verifyPosition(0, 219);
        goToPosition(0, 219);
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        goToPosition(0, 252);
        verifyPosition(0, 115);
        verifyPosition(1, 307);
        verifyPosition(2, 150);
        goToPosition(0, 115);
        verifyPosition(0, 173);
        verifyPosition(1, 307);
        verifyPosition(2, 150);
        goToPosition(0, 173);
        verifyPosition(0, 307);
        verifyPosition(1, 150);
        takeItem("3004");
        goToPosition(0, 307);
        verifyPosition(0, 233);
        verifyPosition(1, 272);
        verifyPosition(2, 150);
        goToPosition(0, 233);
        verifyPosition(0, 272);
        verifyPosition(1, 150);
        goToPosition(0, 272);
        verifyPosition(0, 205);
        verifyPosition(1, 150);
        goToPosition(0, 205);
        verifyPosition(0, 63);
        goToPosition(0, 63);
        prepareLuckSettings(false, false, false);
        attackEnemy("11");
        prepareLuckSettings(false, false, false);
        attackEnemy("11");
        prepareLuckSettings(false, false, false);
        attackEnemy("11");
        prepareLuckSettings(false, false, false);
        attackEnemy("11");
        prepareLuckSettings(false, false, false);
        attackEnemy("11");
        goToPosition(0, 326);
        verifyPosition(0, 150);
        takeItem("3004");
        goToPosition(0, 150);
        verifyPosition(0, 287);
        goToPosition(0, 287);
        verifyPosition(0, 156);
        verifyPosition(1, 222);
        goToPosition(1, 222);
        verifyPosition(0, 240);
        verifyPosition(1, 7);
        goToPosition(0, 240);
        verifyPosition(0, 7);
        goToPosition(0, 7);
        verifyPosition(0, 336);
        verifyPosition(1, 45);
        goToPosition(0, 336);
        doAttributeCheck();
        goToPosition(0, 122);
        verifyPosition(0, 13);
        goToPosition(0, 13);
        verifyPosition(0, 207);
        verifyPosition(1, 84);
        verifyPosition(2, 302);
        verifyPosition(3, 371);
        goToPosition(3, 371);
        verifyPosition(0, 45);
        takeItem("3010");
        goToPosition(0, 45);
        verifyPosition(0, 235);
        verifyPosition(1, 177);
        goToPosition(1, 177);
        verifyPosition(0, 68);
        verifyPosition(1, 227);
        goToPosition(0, 68);
        verifyPosition(0, 318);
        verifyPosition(1, 285);
        verifyPosition(2, 227);
        goToPosition(0, 318);
        verifyPosition(0, 212);
        verifyPosition(1, 363);
        goToPosition(0, 212);
        doAttributeCheck();
        goToPosition(1, 80);
    }

    public void testHappyPath() {
        setUpRandomRolls(Arrays.asList(4, 6, 5, 6, 1, 2, 5, 5, 5, 2, 2, 1, 5, 5, 4, 5, 4, 2, 3, 5, 2, 4, 1, 4, 1, 1, 4, 1, 3, 5, 1, 1, 3, 4, 3, 2, 3, 4, 5, 3, 4, 4, 4,
            1, 3, 3, 2, 6, 5, 4, 5, 3, 1, 2, 2, 3, 3, 4, 5, 4, 3, 2, 2, 5, 5, 6, 4, 1, 4, 6, 1, 4, 5, 6, 1, 4, 5, 5, 4, 5, 4, 2, 3, 2, 1, 3, 3, 4, 5, 3, 2, 1, 1, 1, 5,
            5, 5, 6, 6, 6, 5, 2, 2, 3, 1, 5, 1, 1, 2, 6, 3, 4, 1, 3, 2, 3, 1, 2, 4, 1, 6, 4, 4, 4, 6, 3, 3, 5, 4, 4, 2, 4, 5, 1, 5, 5, 5, 3, 5, 4, 1, 3, 3, 1, 5, 3, 4,
            3, 4, 4, 4, 6, 6, 3, 3, 1, 3, 2, 5, 3, 3, 3, 1, 2, 3, 2, 1, 5, 4, 4, 5, 6, 6, 6, 2, 5, 4, 3, 2, 6, 1, 1, 5, 2, 1, 2, 6, 4, 5, 2, 3, 1, 6, 4, 5, 3, 3, 1, 6,
            4, 3, 4, 2, 1, 3, 2, 5, 1, 1, 5, 5, 4, 2, 3, 5, 3, 3, 2, 1, 3, 4, 5, 1, 1, 2, 2, 3, 4, 3, 2, 3, 3, 4, 3, 4, 2, 2, 4, 1, 2, 4, 1, 4, 6, 5, 1, 1, 3, 3, 1, 3,
            2, 2, 6, 3, 2, 3, 3, 2, 5, 5, 4, 5, 2, 4, 2, 2, 3, 4, 4, 6, 3, 5, 6, 2, 6, 3, 5, 4, 6, 5, 5, 3, 1, 2, 5, 2, 4, 2, 4, 1, 6, 1, 5, 3, 1, 2, 4, 4, 6, 1, 1, 4,
            3, 1, 5, 5, 2, 5, 5, 4, 1, 4, 6, 6, 4, 3, 5, 2, 5, 1, 3, 3, 2, 1, 1, 3, 5, 1, 5, 1, 1, 1, 3, 1, 4, 3, 2, 4, 2, 4, 2, 6, 3, 6, 1, 2, 2, 2, 4, 3, 3, 3, 2, 4,
            1, 1, 3, 2, 2, 2, 5, 2, 2, 4, 1, 4, 2, 5, 1, 4, 1, 1, 3, 1, 6, 3, 6, 4, 6, 1, 4, 5, 4, 2, 6, 5, 5, 2, 5, 1, 3, 3, 1, 2, 2, 5, 5, 3, 3, 2, 2, 5, 5, 4, 2, 2,
            3, 3, 2, 6, 1, 2, 6, 6, 5, 1, 5, 1, 4, 3, 2, 4, 4, 6, 2, 1, 1, 2, 1, 3, 3, 2, 6, 3, 3, 3, 4, 3, 2, 3, 3, 3, 5, 1, 1, 2, 4, 5, 3, 1, 4, 2, 3, 5, 5, 3, 2, 1,
            1, 1, 3, 2, 3, 1, 1, 4, 4, 6, 4, 3, 1, 5, 5, 5, 2, 1, 1, 6, 4, 3, 3, 5, 4, 5, 1, 5, 2, 1, 3, 1, 1, 4, 4, 3, 2, 4, 2, 4, 1, 3, 4, 6, 4, 5, 5, 3, 2, 5, 3, 4,
            3, 2, 6, 4, 1, 4, 3, 1, 2, 3, 3, 4, 5, 2, 2, 1, 5, 2, 6, 2, 2, 2, 3, 2, 4, 5, 1, 1, 6, 2, 5, 1, 4, 3, 3, 1, 2, 4, 2, 1, 4, 2, 4, 1, 5, 3, 5, 4, 5, 4, 5, 3,
            3, 5, 1, 3, 2, 2, 2, 3, 4, 4, 3, 5, 5, 4, 4, 3, 3, 6, 3, 4, 2, 6, 1, 5, 1, 4, 6, 1, 2, 6, 1, 1, 5, 2, 3, 3, 1, 4, 5, 2, 2, 3, 6, 3, 4, 3, 3, 5, 5, 5, 6, 1,
            2, 2, 2, 1, 4, 5, 5, 3, 1, 6, 6, 1, 5, 5, 4, 2, 4, 3, 5, 3, 5, 5, 1, 1, 3, 5, 3, 1, 4, 3, 4, 5, 5, 5, 1, 1, 4, 3, 5, 5, 2, 5, 1, 2, 4, 6, 4, 6, 3, 5, 1, 5,
            1, 4, 3, 2, 1, 2, 2, 2, 2, 4, 1, 5, 5, 3, 4, 1, 1, 6, 4, 1, 5, 5, 4, 4, 2, 3, 1, 2, 6, 2, 4, 4, 2, 2, 2, 3, 1, 6, 3, 4, 3, 5, 1, 6, 6, 4, 4, 2, 2, 2, 4, 5,
            1, 4, 2, 3, 4, 4, 1, 2, 5, 5, 1, 2, 4, 4, 5, 5, 2, 3, 5, 4, 2, 4, 3, 1, 1, 2, 3, 4, 5, 5, 2, 1, 2, 2, 1, 2, 6, 4, 3, 5, 5, 3, 6, 6, 1, 4, 4, 5, 5, 3, 2, 5,
            6, 5, 5, 3, 3, 3, 5, 3, 3, 4, 4, 4, 5, 5, 2, 5, 4, 5, 4, 3, 4, 2, 3, 1, 2, 2, 1, 3, 6, 5, 4, 4, 4, 5, 4, 1, 1, 5, 1, 5, 2, 3, 4, 1, 1, 5, 3, 1, 3, 5, 5, 1,
            2, 3, 2, 5, 1, 2, 5, 2, 3, 4, 1, 5, 1, 1, 5, 1, 5, 4, 1, 1, 1, 2, 6, 1, 2, 2, 4, 1, 4, 4, 3, 5, 4, 3, 6, 4, 4, 5, 2, 1, 6, 4, 5, 6, 3, 4, 6, 5, 4, 6, 5, 4,
            1, 5, 3, 3, 6, 3, 3, 2, 1, 5, 3, 1, 2, 2, 5, 2, 6, 6, 2, 1, 2, 6, 1, 4, 4, 1, 4, 1, 2, 2, 1, 1, 4, 4, 5, 4, 5, 6, 4, 4, 2, 3, 4, 6, 4, 4, 1, 4, 1, 5, 3, 1));
        goToPosition("0", "background");
        verifyPosition(0, 1);
        goToPosition(0, 1);
        verifyPosition(0, 49);
        verifyPosition(1, 292);
        goToPosition(0, 49);
        verifyPosition(0, 22);
        goToPosition(0, 22);
        verifyPosition(0, 310);
        verifyPosition(1, 107);
        goToPosition(1, 107);
        doAttributeCheck();
        goToPosition(2, 360);
        verifyPosition(0, 136);
        goToPosition(0, 136);
        verifyPosition(0, 275);
        verifyPosition(1, 275);
        goToPosition(1, 275);
        verifyPosition(0, 175);
        goToPosition(0, 175);
        doRandomRoll();
        goToPosition(0, 31);
        doAttributeCheck();
        goToPosition(0, 66);
        doRandomRoll();
        goToPosition(0, 255);
        doAttributeCheck();
        goToPosition(0, 66);
        doRandomRoll();
        goToPosition(0, 255);
        doAttributeCheck();
        goToPosition(0, 66);
        doRandomRoll();
        goToPosition(1, 189);
        verifyPosition(0, 113);
        goToPosition(0, 113);
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        prepareLuckSettings(false, false, false);
        attackEnemy("2");
        goToPosition(0, 237);
        doAttributeCheck();
        goToPosition(0, 94);
        verifyPosition(0, 297);
        verifyPosition(1, 9);
        goToPosition(1, 9);
        doAttributeCheck();
        goToPosition(1, 73);
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        prepareLuckSettings(false, false, false);
        attackEnemy("3");
        goToPosition(0, 196);
        verifyPosition(0, 120);
        goToPosition(0, 120);
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        prepareLuckSettings(false, false, false);
        attackEnemy("4");
        goToPosition(0, 61);
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        prepareLuckSettings(false, false, false);
        attackEnemy("5");
        goToPosition(0, 261);
        verifyPosition(0, 374);
        verifyPosition(1, 82);
        goToPosition(0, 374);
        prepareLuckSettings(false, false, false);
        attackEnemy("6");
        prepareLuckSettings(false, false, false);
        attackEnemy("6");
        prepareLuckSettings(false, false, false);
        attackEnemy("6");
        prepareLuckSettings(false, false, false);
        attackEnemy("6");
        goToPosition(0, 52);
        verifyPosition(0, 36);
        verifyPosition(1, 82);
        goToPosition(0, 36);
        verifyPosition(0, 82);
        takeItem("3004");
        goToPosition(0, 82);
        verifyPosition(0, 229);
        verifyPosition(1, 304);
        goToPosition(1, 304);
        verifyPosition(1, 27);
        verifyPosition(2, 152);
        verifyPosition(3, 355);
        goToPosition(3, 355);
        doAttributeCheck();
        goToPosition(0, 100);
        prepareLuckSettings(false, false, false);
        attackEnemy("7");
        prepareLuckSettings(false, false, false);
        attackEnemy("7");
        prepareLuckSettings(false, false, false);
        attackEnemy("7");
        goToPosition(0, 19);
        verifyPosition(0, 70);
        verifyPosition(1, 328);
        goToPosition(0, 70);
        verifyPosition(0, 328);
        goToPosition(0, 328);
        verifyPosition(0, 27);
        verifyPosition(1, 152);
        verifyPosition(2, 229);
        goToPosition(1, 152);
        verifyPosition(0, 117);
        goToPosition(0, 117);
        verifyPosition(0, 179);
        verifyPosition(1, 229);
        goToPosition(0, 179);
        verifyPosition(0, 12);
        verifyPosition(1, 214);
        goToPosition(0, 12);
        verifyPosition(0, 246);
        verifyPosition(1, 346);
        goToPosition(0, 246);
        verifyPosition(0, 186);
        verifyPosition(1, 346);
        goToPosition(0, 186);
        prepareLuckSettings(false, false, false);
        attackEnemy("9");
        prepareLuckSettings(false, false, false);
        attackEnemy("9");
        prepareLuckSettings(false, false, false);
        attackEnemy("8");
        prepareLuckSettings(false, false, false);
        attackEnemy("8");
        prepareLuckSettings(false, false, false);
        attackEnemy("8");
        goToPosition(0, 142);
        verifyPosition(0, 124);
        verifyPosition(1, 171);
        verifyPosition(2, 300);
        verifyPosition(3, 346);
        goToPosition(2, 300);
        verifyPosition(0, 124);
        verifyPosition(1, 346);
        goToPosition(1, 346);
        verifyPosition(0, 59);
        verifyPosition(1, 150);
        goToPosition(0, 59);
        verifyPosition(0, 91);
        verifyPosition(1, 150);
        goToPosition(0, 91);
        doAttributeCheck();
        goToPosition(0, 332);
        verifyPosition(0, 219);
        goToPosition(0, 219);
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        prepareLuckSettings(false, false, false);
        attackEnemy("10");
        goToPosition(0, 252);
        verifyPosition(0, 115);
        verifyPosition(1, 307);
        verifyPosition(2, 150);
        goToPosition(0, 115);
        verifyPosition(0, 173);
        verifyPosition(1, 307);
        verifyPosition(2, 150);
        goToPosition(0, 173);
        verifyPosition(0, 307);
        verifyPosition(1, 150);
        takeItem("3004");
        goToPosition(0, 307);
        verifyPosition(0, 233);
        verifyPosition(1, 272);
        verifyPosition(2, 150);
        goToPosition(0, 233);
        verifyPosition(0, 272);
        verifyPosition(1, 150);
        goToPosition(0, 272);
        verifyPosition(0, 205);
        verifyPosition(1, 150);
        goToPosition(0, 205);
        verifyPosition(0, 63);
        goToPosition(0, 63);
        prepareLuckSettings(false, false, false);
        attackEnemy("11");
        prepareLuckSettings(false, false, false);
        attackEnemy("11");
        prepareLuckSettings(false, false, false);
        attackEnemy("11");
        prepareLuckSettings(false, false, false);
        attackEnemy("11");
        prepareLuckSettings(false, false, false);
        attackEnemy("11");
        prepareLuckSettings(false, false, false);
        attackEnemy("11");
        goToPosition(0, 326);
        verifyPosition(0, 150);
        takeItem("3004");
        goToPosition(0, 150);
        verifyPosition(0, 287);
        goToPosition(0, 287);
        verifyPosition(0, 156);
        verifyPosition(1, 222);
        goToPosition(1, 222);
        verifyPosition(0, 240);
        verifyPosition(1, 7);
        goToPosition(0, 240);
        verifyPosition(0, 7);
        goToPosition(0, 7);
        verifyPosition(0, 336);
        verifyPosition(1, 45);
        goToPosition(0, 336);
        doAttributeCheck();
        goToPosition(1, 76);
        prepareLuckSettings(false, false, false);
        attackEnemy("14");
        prepareLuckSettings(false, false, false);
        attackEnemy("14");
        prepareLuckSettings(false, false, false);
        attackEnemy("14");
        prepareLuckSettings(false, false, false);
        attackEnemy("14");
        goToPosition(0, 341);
        verifyPosition(0, 13);
        takeItem("3009");
        goToPosition(0, 13);
        verifyPosition(0, 207);
        verifyPosition(1, 84);
        verifyPosition(2, 302);
        verifyPosition(3, 371);
        goToPosition(3, 371);
        verifyPosition(0, 45);
        takeItem("3010");
        goToPosition(0, 45);
        verifyPosition(0, 235);
        verifyPosition(1, 177);
        goToPosition(1, 177);
        verifyPosition(0, 68);
        verifyPosition(1, 227);
        goToPosition(0, 68);
        verifyPosition(0, 318);
        verifyPosition(1, 285);
        verifyPosition(2, 227);
        goToPosition(0, 318);
        verifyPosition(0, 212);
        verifyPosition(1, 363);
        goToPosition(0, 212);
        doAttributeCheck();
        goToPosition(0, 15);
        verifyPosition(0, 285);
        verifyPosition(1, 227);
        takeItem("3004");
        goToPosition(1, 227);
        verifyPosition(0, 37);
        verifyPosition(1, 397);
        goToPosition(0, 37);
        verifyPosition(0, 118);
        verifyPosition(1, 397);
        goToPosition(0, 118);
        prepareLuckSettings(false, false, false);
        attackEnemy("15");
        prepareLuckSettings(false, false, false);
        attackEnemy("15");
        prepareLuckSettings(false, false, false);
        attackEnemy("15");
        prepareLuckSettings(false, false, false);
        attackEnemy("15");
        goToPosition(0, 348);
        verifyPosition(0, 397);
        takeItem("3004");
        goToPosition(0, 397);
        verifyPosition(0, 305);
        verifyPosition(1, 93);
        goToPosition(1, 93);
        verifyPosition(0, 146);
        verifyPosition(1, 305);
        goToPosition(0, 146);
        prepareLuckSettings(false, false, false);
        attackEnemy("16");
        prepareLuckSettings(false, false, false);
        attackEnemy("17");
        prepareLuckSettings(false, false, false);
        attackEnemy("18");
        prepareLuckSettings(false, false, false);
        attackEnemy("19");
        prepareLuckSettings(false, false, false);
        attackEnemy("20");
        goToPosition(0, 18);
        verifyPosition(0, 57);
        verifyPosition(1, 184);
        verifyPosition(2, 305);
        goToPosition(0, 57);
        verifyPosition(1, 184);
        verifyPosition(2, 305);
        takeItem("3011");
        goToPosition(1, 184);
        verifyPosition(0, 305);
        goToPosition(0, 305);
        verifyPosition(0, 43);
        verifyPosition(1, 373);
        goToPosition(1, 373);
        verifyPosition(0, 43);
        takeItem("3012");
        takeItem("3013");
        takeItem("3014");
        goToPosition(0, 43);
        verifyPosition(0, 126);
        verifyPosition(1, 187);
        verifyPosition(2, 157);
        verifyPosition(3, 221);
        goToPosition(1, 187);
        verifyPosition(0, 126);
        verifyPosition(1, 157);
        verifyPosition(2, 221);
        goToPosition(0, 126);
        verifyPosition(0, 10);
        verifyPosition(1, 281);
        goToPosition(1, 281);
        verifyPosition(0, 3);
        goToPosition(0, 3);
        verifyPosition(0, 369);
        verifyPosition(1, 200);
        goToPosition(0, 369);
        prepareLuckSettings(false, false, false);
        attackEnemy("23");
        prepareLuckSettings(false, false, false);
        attackEnemy("23");
        prepareLuckSettings(false, false, false);
        attackEnemy("23");
        prepareLuckSettings(false, false, false);
        attackEnemy("23");
        goToPosition(0, 352);
        giveResponse("25", 3335);
        goToPosition(0, 25);
        verifyPosition(0, 134);
        verifyPosition(1, 204);
        goToPosition(1, 204);
        verifyPosition(0, 111);
        verifyPosition(1, 32);
        goToPosition(1, 32);
        verifyPosition(0, 239);
        verifyPosition(1, 267);
        goToPosition(0, 239);
        doAttributeCheck();
        goToPosition(0, 248);
        verifyPosition(0, 320);
        verifyPosition(1, 385);
        goToPosition(1, 385);
        verifyPosition(0, 362);
        goToPosition(0, 362);
        verifyPosition(0, 95);
        verifyPosition(1, 329);
        goToPosition(1, 329);
        prepareLuckSettings(false, false, false);
        attackEnemy("24");
        prepareLuckSettings(false, false, false);
        attackEnemy("24");
        prepareLuckSettings(false, false, false);
        attackEnemy("24");
        prepareLuckSettings(false, false, false);
        attackEnemy("24");
        prepareLuckSettings(false, false, false);
        attackEnemy("24");
        prepareLuckSettings(false, false, false);
        attackEnemy("24");
        applyItem("1007");
        goToPosition(0, 209);
        verifyPosition(0, 129);
        verifyPosition(1, 351);
        takeItem("3017");
        takeItem("3018");
        goToPosition(0, 129);
        verifyPosition(0, 264);
        verifyPosition(1, 351);
        goToPosition(0, 264);
        verifyPosition(0, 190);
        verifyPosition(1, 351);
        goToPosition(0, 190);
        verifyPosition(0, 279);
        verifyPosition(1, 230);
        goToPosition(0, 279);
        prepareLuckSettings(false, false, false);
        attackEnemy("28");
        prepareLuckSettings(false, false, false);
        attackEnemy("28");
        prepareLuckSettings(false, false, false);
        attackEnemy("28");
        goToPosition(0, 339);
        verifyPosition(0, 75);
        verifyPosition(1, 167);
        goToPosition(1, 167);
        verifyPosition(0, 144);
        verifyPosition(1, 230);
        goToPosition(0, 144);
        verifyPosition(0, 359);
        verifyPosition(1, 230);
        goToPosition(0, 359);
        verifyPosition(0, 60);
        verifyPosition(1, 263);
        goToPosition(0, 60);
        verifyPosition(0, 263);
        takeItem("3004");
        goToPosition(0, 263);
        verifyPosition(0, 315);
        verifyPosition(1, 289);
        goToPosition(0, 315);
        verifyPosition(0, 195);
        goToPosition(0, 195);
        verifyPosition(1, 247);
        verifyPosition(3, 112);
        goToPosition(3, 112);
        verifyPosition(0, 323);
        verifyPosition(1, 178);
        goToPosition(1, 178);
        verifyPosition(0, 247);
        goToPosition(0, 247);
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        prepareLuckSettings(false, false, false);
        attackEnemy("29a");
        goToPosition(0, 180);
        verifyPosition(0, 282);
        verifyPosition(1, 44);
        goToPosition(0, 282);
        verifyPosition(0, 44);
        takeItem("3004");
        goToPosition(0, 44);
        verifyPosition(0, 340);
        verifyPosition(1, 155);
        goToPosition(1, 155);
        verifyPosition(0, 119);
        verifyPosition(1, 288);
        goToPosition(0, 119);
        verifyPosition(0, 288);
        takeItem("3022");
        goToPosition(0, 288);
        verifyPosition(0, 185);
        verifyPosition(1, 347);
        goToPosition(1, 347);
        verifyPosition(0, 114);
        goToPosition(0, 114);
        verifyPosition(0, 251);
        goToPosition(0, 251);
        verifyPosition(0, 90);
        verifyPosition(1, 333);
        goToPosition(0, 90);
        verifyPosition(0, 333);
        takeItem("3004");
        goToPosition(0, 333);
        verifyPosition(0, 96);
        verifyPosition(1, 375);
        goToPosition(0, 96);
        verifyPosition(0, 215);
        verifyPosition(1, 375);
        goToPosition(0, 215);
        verifyPosition(0, 394);
        verifyPosition(1, 375);
        goToPosition(0, 394);
        verifyPosition(0, 375);
        goToPosition(0, 375);
        verifyPosition(0, 168);
        verifyPosition(1, 138);
        goToPosition(0, 168);
        verifyPosition(0, 77);
        verifyPosition(1, 138);
        goToPosition(0, 77);
        doAttributeCheck();
        goToPosition(0, 245);
        verifyPosition(0, 8);
        goToPosition(0, 8);
        verifyPosition(0, 306);
        verifyPosition(1, 138);
        takeItem("3023");
        goToPosition(0, 306);
        prepareLuckSettings(false, false, false);
        attackEnemy("34");
        prepareLuckSettings(false, false, false);
        attackEnemy("34");
        prepareLuckSettings(false, false, false);
        attackEnemy("34");
        goToPosition(0, 85);
        verifyPosition(0, 364);
        verifyPosition(1, 138);
        goToPosition(0, 364);
        doRandomRoll();
        goToPosition(0, 103);
        doAttributeCheck();
        goToPosition(0, 356);
        prepareLuckSettings(false, false, false);
        attackEnemy("35");
        prepareLuckSettings(false, false, false);
        attackEnemy("35");
        prepareLuckSettings(false, false, false);
        attackEnemy("35");
        prepareLuckSettings(false, false, false);
        attackEnemy("35");
        prepareLuckSettings(false, false, false);
        attackEnemy("35");
        prepareLuckSettings(false, false, false);
        attackEnemy("35");
        goToPosition(0, 236);
        verifyPosition(0, 21);
        goToPosition(0, 21);
        verifyPosition(0, 372);
        verifyPosition(1, 50);
        goToPosition(0, 372);
        verifyPosition(0, 141);
        goToPosition(0, 141);
        verifyPosition(0, 208);
        verifyPosition(1, 69);
        goToPosition(0, 208);
        verifyPosition(0, 53);
        verifyPosition(1, 147);
        verifyPosition(2, 69);
        goToPosition(0, 53);
        verifyPosition(0, 147);
        verifyPosition(1, 69);
        goToPosition(1, 69);
        verifyPosition(0, 182);
        verifyPosition(1, 109);
        goToPosition(0, 182);
        verifyPosition(0, 311);
        verifyPosition(1, 109);
        goToPosition(0, 311);
        prepareLuckSettings(false, false, false);
        attackEnemy("36");
        prepareLuckSettings(false, false, false);
        attackEnemy("36");
        prepareLuckSettings(false, false, false);
        attackEnemy("36");
        goToPosition(0, 262);
        verifyPosition(0, 109);
        takeItem("3004");
        goToPosition(0, 109);
        verifyPosition(0, 143);
        verifyPosition(1, 386);
        goToPosition(0, 143);
        verifyPosition(0, 370);
        verifyPosition(1, 386);
        goToPosition(0, 370);
        verifyPosition(0, 16);
        goToPosition(0, 16);
        verifyPosition(0, 88);
        goToPosition(0, 88);
        verifyPosition(0, 41);
        verifyPosition(1, 149);
        verifyPosition(2, 388);
        goToPosition(1, 149);
        verifyPosition(0, 388);
        takeItem("3025");
        goToPosition(0, 388);
        verifyPosition(0, 309);
        verifyPosition(1, 58);
        goToPosition(1, 58);
        verifyPosition(0, 106);
        goToPosition(0, 106);
        verifyPosition(0, 314);
        verifyPosition(1, 228);
        goToPosition(0, 314);
        verifyPosition(0, 228);
        goToPosition(0, 228);
        doAttributeCheck();
        goToPosition(1, 79);
        prepareLuckSettings(false, false, false);
        attackEnemy("37");
        prepareLuckSettings(false, false, false);
        attackEnemy("37");
        prepareLuckSettings(false, false, false);
        attackEnemy("37");
        prepareLuckSettings(false, false, false);
        attackEnemy("37");
        prepareLuckSettings(false, false, false);
        attackEnemy("37");
        prepareLuckSettings(false, false, false);
        attackEnemy("37");
        prepareLuckSettings(false, false, false);
        attackEnemy("37");
        goToPosition(0, 65);
        verifyPosition(0, 201);
        verifyPosition(1, 211);
        goToPosition(1, 211);
        prepareLuckSettings(false, false, false);
        attackEnemy("38");
        prepareLuckSettings(false, false, false);
        attackEnemy("38");
        prepareLuckSettings(false, false, false);
        attackEnemy("38");
        prepareLuckSettings(false, false, false);
        attackEnemy("38");
        prepareLuckSettings(false, false, false);
        attackEnemy("38");
        prepareLuckSettings(false, false, false);
        attackEnemy("38");
        prepareLuckSettings(false, false, false);
        attackEnemy("38");
        goToPosition(0, 354);
        verifyPosition(0, 238);
        goToPosition(0, 238);
        verifyPosition(0, 125);
        goToPosition(0, 125);
        verifyPosition(0, 11);
        goToPosition(0, 11);
        verifyPosition(0, 278);
        verifyPosition(1, 278);
        verifyPosition(2, 92);
        verifyPosition(3, 92);
        verifyPosition(4, 345);
        verifyPosition(5, 345);
        goToPosition(4, 345);
        verifyPosition(0, 35);
        goToPosition(0, 35);
        giveResponse("249", 22243);
        goToPosition(0, 249);
        giveResponse("358", 2293);
        goToPosition(0, 358);
        giveResponse("176", 8917);
        goToPosition(0, 176);
        prepareLuckSettings(false, false, false);
        attackEnemy("39");
        prepareLuckSettings(false, false, false);
        attackEnemy("39");
        prepareLuckSettings(false, false, false);
        attackEnemy("39");
        goToPosition(0, 127);
        prepareLuckSettings(false, false, false);
        attackEnemy("40");
        prepareLuckSettings(false, false, false);
        attackEnemy("40");
        prepareLuckSettings(false, false, false);
        attackEnemy("40");
        prepareLuckSettings(false, false, false);
        attackEnemy("40");
        prepareLuckSettings(false, false, false);
        attackEnemy("40");
        goToPosition(0, 303);
        verifyPosition(1, 220);
        verifyPosition(2, 81);
        verifyPosition(3, 48);
        goToPosition(2, 81);
        verifyPosition(0, 48);
        goToPosition(0, 48);
        verifyPosition(0, 377);
        verifyPosition(1, 257);
        verifyPosition(2, 158);
        verifyPosition(3, 116);
        goToPosition(0, 377);
        verifyPosition(0, 232);
        verifyPosition(1, 319);
        goToPosition(0, 232);
        verifyPosition(0, 291);
        verifyPosition(1, 28);
        goToPosition(1, 28);
        verifyPosition(0, 71);
        goToPosition(0, 71);
        verifyPosition(0, 188);
        goToPosition(0, 188);
        prepareLuckSettings(false, false, false);
        attackEnemy("41");
        prepareLuckSettings(false, false, false);
        attackEnemy("41");
        prepareLuckSettings(false, false, false);
        attackEnemy("41");
        prepareLuckSettings(false, false, false);
        attackEnemy("41");
        prepareLuckSettings(false, false, false);
        attackEnemy("41");
        prepareLuckSettings(false, false, false);
        attackEnemy("41");
        prepareLuckSettings(false, false, false);
        attackEnemy("41");
        goToPosition(0, 400);
    }

}
